# Site settings
title: ArgumentError
header-img: img/home-bg.png
email: alicekb01@gmail.com
copyright_name: Alicekb
description: > # this means to ignore newlines until "baseurl:"
  A blog about my experience learning to program.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Alicekb
learn_profile: Alicekb
email_username: alicekb01@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
