# Site settings
title: Alice's Adventure In Learn.co
header-img: img/home-bg.png
email: alicekb01@gmail.com
copyright_name: AliceKB
description: > # this means to ignore newlines until "baseurl:"
  A blog about my learning.co experience
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AliceKB
learn_profile: AliceKB
email_username: alicekb01@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
